### ISSUE TITLE
Currently, the SSM resolution must always resolve to String.  Boolean and Numerics become strings

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/uc3-ssm#16]
The true/false value is not resolving properly.  In DEV, we use docker and do not have SSL.  In Prod/Stage, we need SSL.

```yml
  opensearch:
    host: "{!SSM: objhealth/opensearch_host}"
    user: "{!SSM: objhealth/opensearch_user}"
    password: "{!SSM: objhealth/opensearch_password}"
    transport_options:
      ssl: 
        verify: "{!SSM: objhealth/opensearch_ssl}"
```

As a workaround, I had to do the following

```rb
    osconfig = @config.fetch("opensearch", {})
    osconfig[:transport_options] = osconfig.fetch(:transport_options, {})
    osconfig[:transport_options][:ssl] = osconfig[:transport_options].fetch(:ssl, {})
    osconfig[:transport_options][:ssl][:verify] = osconfig[:transport_options][:ssl].fetch(:verify, "false") == "true"
    @osclient = OpenSearch::Client.new(@config.fetch("opensearch", {}))
```

If we solve this in the ruby implementation, we should also resolve this in the Java implementation.
